# Podfile for 鑫琳医生 iOS App
# 达摩院语音方案集成

platform :ios, '17.0'

use_frameworks!
inhibit_all_warnings!

target 'xinlingyisheng' do
  # ONNX Runtime Swift - 用于 FSMN-VAD 模型推理
  pod 'ONNXRuntimeSwift', '~> 0.2.0'

  # 如需使用 Swift Package Manager 的依赖，可以在此添加
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # 设置最低 iOS 版本
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'

      # 仅支持 64 位架构
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      config.build_settings['EXCLUDED_ARCHS'] = 'i386 armv7 armv7s'
    end
  end
end
