-- ========== 患者与医生关联表 ==========
-- 创建日期: 2026-02-09
-- 说明: 创建医生（admin_users）与患者（users）的多对多关联表
--
-- 此迁移创建：
-- 1. doctor_patient_relationships 表 - 医生-患者关联关系
-- 2. 相关索引和外键约束
-- 3. 允许多对多关联（一个患者可以有多个医生，一个医生可以有多个患者）
--
-- 注意：此脚本不包含历史数据迁移

-- 1. 创建医生-患者关联表
CREATE TABLE IF NOT EXISTS doctor_patient_relationships (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,

    -- 关联字段
    doctor_id INTEGER NOT NULL,           -- 医生 ID（关联 admin_users）
    patient_id INTEGER NOT NULL,          -- 患者 ID（关联 users）

    -- 关系属性
    relationship_type VARCHAR(20) DEFAULT 'primary',  -- 关系类型: primary（主治）, consulting（会诊）, temporary（临时）
    is_active BOOLEAN DEFAULT TRUE,                   -- 关系是否有效
    assigned_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(), -- 关联建立时间
    assigned_by INTEGER,                              -- 创建人 ID（可为空，系统自动创建时）

    -- 备注
    notes TEXT,                                      -- 备注信息

    -- 时间戳
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- 唯一约束：一个医生对一个患者只能有一条活跃的 primary 关系
    -- 但允许有 consulting 或 temporary 关系
    CONSTRAINT unique_doctor_patient_primary
        UNIQUE (doctor_id, patient_id)
        WHERE is_active = TRUE AND relationship_type = 'primary'
);

-- 2. 添加外键约束
ALTER TABLE doctor_patient_relationships
ADD CONSTRAINT fk_doctor_patient_doctor
FOREIGN KEY (doctor_id)
REFERENCES admin_users(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE doctor_patient_relationships
ADD CONSTRAINT fk_doctor_patient_patient
FOREIGN KEY (patient_id)
REFERENCES users(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE doctor_patient_relationships
ADD CONSTRAINT fk_doctor_patient_assigned_by
FOREIGN KEY (assigned_by)
REFERENCES admin_users(id)
ON DELETE SET NULL
ON UPDATE CASCADE;

-- 3. 创建索引（提升查询性能）
CREATE INDEX IF NOT EXISTS idx_doctor_patient_doctor_id
ON doctor_patient_relationships(doctor_id);

CREATE INDEX IF NOT EXISTS idx_doctor_patient_patient_id
ON doctor_patient_relationships(patient_id);

CREATE INDEX IF NOT EXISTS idx_doctor_patient_is_active
ON doctor_patient_relationships(is_active);

CREATE INDEX IF NOT EXISTS idx_doctor_patient_relationship_type
ON doctor_patient_relationships(relationship_type);

CREATE INDEX IF NOT EXISTS idx_doctor_patient_doctor_active
ON doctor_patient_relationships(doctor_id, is_active)
WHERE is_active = TRUE;

-- 4. 添加表和字段注释
COMMENT ON TABLE doctor_patient_relationships IS '医生-患者关联关系表（多对多）';
COMMENT ON COLUMN doctor_patient_relationships.doctor_id IS '医生 ID，关联 admin_users.id';
COMMENT ON COLUMN doctor_patient_relationships.patient_id IS '患者 ID，关联 users.id';
COMMENT ON COLUMN doctor_patient_relationships.relationship_type IS '关系类型: primary（主治）, consulting（会诊）, temporary（临时）';
COMMENT ON COLUMN doctor_patient_relationships.is_active IS '关系是否有效（禁用后医生不可见该患者）';
COMMENT ON COLUMN doctor_patient_relationships.assigned_at IS '关联建立时间';
COMMENT ON COLUMN doctor_patient_relationships.assigned_by IS '创建人 ID（关联 admin_users.id）';
COMMENT ON COLUMN doctor_patient_relationships.notes IS '备注信息';

-- 5. 创建 updated_at 触发器（自动更新时间戳）
CREATE OR REPLACE FUNCTION update_doctor_patient_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_doctor_patient_updated_at
BEFORE UPDATE ON doctor_patient_relationships
FOR EACH ROW
EXECUTE FUNCTION update_doctor_patient_updated_at();

-- 6. 验证表结构
SELECT
    column_name,
    data_type,
    is_nullable,
    column_default
FROM information_schema.columns
WHERE table_name = 'doctor_patient_relationships'
ORDER BY ordinal_position;

-- 7. 验证索引
SELECT
    indexname,
    indexdef
FROM pg_indexes
WHERE tablename = 'doctor_patient_relationships';
